---
- name: Include vars
  ansible.builtin.include_vars:
    file: '{{ experience.path }}'

- name: Extract information
  set_fact:
    __experience_bucket: '{{ experience.path.split("/")[0] }}'
    __experience_name: '{{ experience.path.split("/")[3] }}'

- name: 'Check if an Execution Environment is provided for {{ __experience_bucket }}.{{ __experience_name }}'
  ansible.builtin.file:
    path: "{{ experience.path.replace('setup.yml', 'exec_env') }}"
  failed_when: false
  register: __experience_exec_env

- name: Create temp dir
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: tmp_dir
  apply:
    delegate_to: builder

- name: Copy Execution Experience over
  ansible.builtin.copy:
    src: "{{ experience.path.replace('setup.yml', 'exec_env') }}/execution_environment.yml"
    dest: "{{ tmp_dir.path }}"
  apply:
    delegate_to: builder

- name: Generate and publish Execution Environment
  ansible.builtin.include_role:
    name: infra.ee_utilities.ee_builder
  vars:
    ee_builder_dir_clean: false
    ee_builder_dir: "{{ experience.path.replace('setup.yml', 'exec_env') }}"
    ee_update_base_images: false
    ee_pull_collections_from_hub: false
    ee_image_push: false
    ee_list:
      - name: "{{ __experience_bucket }}.{{ __experience_name }}"
        skip_generation: true
  when: __experience_exec_env.state == 'directory'

- name: Execute automation controller resource configuration
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
  vars:
    controller_configuration_async_delay: 1
    controller_configuration_async_retries: 30
