---
- name: Include vars
  ansible.builtin.include_vars:
    file: '{{ experience.path }}'

- name: Execute automation controller resource configuration
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
  vars:
    controller_configuration_async_delay: 1
    controller_configuration_async_retries: 30
