---
- name: Seeding Red Hat Playbooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: 'group_vars/network'
      when: "'Network' is in seed_domain | default([])"

    - name: Display message
      debug:
        msg: "{{ test | default('fail') }}"
      when: "'Network' is in seed_domain | default([])"

    - name: Display message
      debug:
        msg: "Linux"
      when: "'Linux' is in seed_domain | default([])"

    - name: Display message
      debug:
        msg: "Cloud"
      when: "'Cloud' is in seed_domain | default([])"
