---
- name: Seeding Red Hat Playbooks
  hosts: localhost
  gather_facts: false
  tasks:

    - block:
        - name: Get Red Hat Networking Supported Playbooks
          ansible.builtin.git:
            repo: '{{ seed_network_cac_url }}'
            dest: '{{ seed_network_cac_dir }}'

        - name: Include vars
          ansible.builtin.include_vars:
            dir: '{{ seed_network_cac_dir }}'
            extensions:
              - yml
              - yaml
            ignore_unknown_extensions: true

        - name: Display projects
          debug:
            msg: "{{ controller_projects | default('fail') }}"

        - name: Display job templates
          debug:
            msg: "{{ controller_templates | default('fail') }}"

        - name: Execute automation controller resource configuration
          ansible.builtin.include_role:
            name: infra.controller_configuration.dispatch

      when: "'Network' is in seed_domain | default([])"

    - name: Display message
      debug:
        msg: "Linux"
      when: "'Linux' is in seed_domain | default([])"

    - name: Display message
      debug:
        msg: "Cloud"
      when: "'Cloud' is in seed_domain | default([])"
