---
- name: Seeding Partner Playbooks
  hosts: localhost
  gather_facts: false
  tasks:

    - block:
        - name: Get Dell Ceritifed Playbooks
          ansible.builtin.git:
            repo: '{{ seed_dell_cac_url }}'
            dest: '{{ seed_dell_cac_dir }}'

        - name: Include vars
          ansible.builtin.include_vars:
            dir: '{{ seed_dell_cac_dir }}'
            extensions:
              - yml
              - yaml
            ignore_unknown_extensions: true

        - name: Execute automation controller resource configuration
          ansible.builtin.include_role:
            name: infra.controller_configuration.dispatch
          vars:
            controller_configuration_async_delay: 1
            controller_configuration_async_retries: 30

      when: "'Dell' is in seed_partners | default([])"

    - block:
        - name: Get F5 ceritifed Playbooks
          ansible.builtin.git:
            repo: '{{ seed_f5_cac_url }}'
            dest: '{{ seed_f5_cac_dir }}'

        - name: Include vars
          ansible.builtin.include_vars:
            dir: '{{ seed_f5_cac_dir }}'
            extensions:
              - yml
              - yaml
            ignore_unknown_extensions: true

        - name: Execute automation controller resource configuration
          ansible.builtin.include_role:
            name: infra.controller_configuration.dispatch
          vars:
            controller_configuration_async_delay: 1
            controller_configuration_async_retries: 30

      when: "'F5' is in seed_partners | default([])"

    - block:
        - name: Get dynatrace ceritifed Playbooks
          ansible.builtin.git:
            repo: '{{ seed_dynatrace_cac_url }}'
            dest: '{{ seed_dynatrace_cac_dir }}'

        - name: Include vars
          ansible.builtin.include_vars:
            dir: '{{ seed_dynatrace_cac_dir }}'
            extensions:
              - yml
              - yaml
            ignore_unknown_extensions: true

        - name: Execute automation controller resource configuration
          ansible.builtin.include_role:
            name: infra.controller_configuration.dispatch
          vars:
            controller_configuration_async_delay: 1
            controller_configuration_async_retries: 30

      when: "'Dynatrace' is in seed_partners | default([])"
