---
- name: Seeding Custom Playbooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Custom Playbooks content
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ seed_custom_cac_url.split("/")[-1] }}'

    - name: Get all experiences in collection
      ansible.builtin.find:
        paths: .
        patterns: setup.yml
        recurse: true
      register: experiences

    - name: Include vars
      ansible.builtin.include_vars:
        file: '{{ seed_custom_cac_url.split("/")[-1] }}/{{ item.path }}'
      loop: '{{ experiences.files }}'

    - name: Execute automation controller resource configuration
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
      vars:
        controller_configuration_async_delay: 1
        controller_configuration_async_retries: 30
