---
- name: Seeding Custom Playbooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Custom Playbooks content
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ seed_custom_cac_url.split("/")[-1] }}'

    - name: Include vars
      ansible.builtin.include_vars:
        dir: '{{ seed_custom_cac_url.split("/")[-1] }}/extensions/experiences/patching_os'
        extensions:
          - yml
          - yaml
        ignore_unknown_extensions: true

    - name: Execute automation controller resource configuration
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
      vars:
        controller_configuration_async_delay: 1
        controller_configuration_async_retries: 30
