---
- name: Seeding Custom Playbooks
  hosts: locahost
  gather_facts: false
  tasks:

    - name: Get Custom Playbooks content
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ seed_custom_cac_url.split("/")[-1] }}'


    - name: Get all experiences in collection
      ansible.builtin.find:
        paths: '{{ seed_custom_cac_url.split("/")[-1] }}'
        patterns: setup.yml
        recurse: true
      register: experiences

    - name: Load experiences
      ansible.builtin.include_tasks: load_experience.yml
      loop: '{{ experiences.files }}'
      loop_control:
        loop_var: experience
