---
- name: Seeding Custom Playbooks
  hosts: builder
  gather_facts: false
  tasks:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: tmp_dir

    - name: Get Custom Playbooks content
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ tmp_dir.path }}/{{ seed_custom_cac_url.split("/")[-1] }}'

    - name: Get all experiences in collection
      ansible.builtin.find:
        paths: '{{ tmp_dir.path }}/{{ seed_custom_cac_url.split("/")[-1] }}'
        patterns: setup.yml
        recurse: true
      register: experiences

    - name: Load experiences
      ansible.builtin.include_tasks: load_experience.yml
      loop: '{{ experiences.files }}'
      loop_control:
        loop_var: experience
