---
- name: Seeding Red Hat Playbooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display message
      debug:
        msg: "Network"
      when: 'Network' is in seed_domain | default([])

    - name: Display message
      debug:
        msg: "Linux"
      when: 'Linux' is in seed_domain | default([])

    - name: Display message
      debug:
        msg: "Cloud"
      when: 'Cloud' is in seed_domain | default([])
