---
- name: Seeding Custom Playbooks
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: tmp_dir
      delegate_to: builder

    - name: Get Custom Playbooks content
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ seed_custom_cac_url.split("/")[-1] }}'

    - name: Get all experiences in collection
      ansible.builtin.find:
        paths: '{{ seed_custom_cac_url.split("/")[-1] }}'
        patterns: setup.yml
        recurse: true
      register: experiences

    - name: Load xperiences
      ansible.builtin.include_tasks: load_experience.yml
      loop: '{{ experiences.files }}'
      loop_control:
        loop_var: experience
      vars:
        tmp_dir_path: "{{ tmp_dir.path }}"
